spring:
  data:
    redis:
      client-type: jedis
      host: "localhost"
      port: 6379
      password: "password"
app:
  web-socket:
    prefix:
      application: /app
      client: /topic
  only-once-event:
    event-duration-millis: 10000
    max-events: 10000
    key-prefix: "only-once"
    web-socket:
      element: "only-once"
    event-queue:
      num-workers: 2
    # for testing
    disable-bean:
      event-expiry-service: false
      event-queue-snapshot-service: false
      only-once-event-service: false
      event-publisher: false
  strictly-once-event:
    event-duration-millis: 10000
    max-events: 10000
    key-prefix: "strictly-once"
    web-socket:
      element: "strictly-once"
    event-queue:
      num-workers: 2
  time-sync:
    num-frames: 20
    message-prefix: "/topic/time"
  redis:
    functions-resource: redis/redis_functions.lua
    retry:
      # configured to do 5 attempts (t = 0, 0.25, 0.63, 1.19, 2.03 sec)
      initial-interval: 250
      multiplier: 1.5
      num-attempts: 5
    # for testing
    disable-bean:
      redis-connection-factory: false
      string-redis-template: false
      string-long-redis-template: false


logging:
  level:
    org:
      springframework: info
    com:
      ericgha: info