spring:
  data:
    redis:
      client-type: jedis
      host: "localhost"
      port: 6379
      password: "password"
app:
  web-socket:
    prefix:
      application: /app
      client: /topic
  only-once-event:
    event-duration-millis: 10000
    max-events: 10000
    key-prefix: "only-once"
    web-socket:
      element: "only-once"
    event-map:
      retry:
        # configured to do 5 attempts (t = 0, 0.5, 1.25, 2.375, 4.063 sec)
        initial-interval: 500
        multiplier: 1.5
        num-attempts: 5
    event-queue:
      retry:
        # 5 attempts with 3ms delay between each
        num-attempts: 5
        interval: 3
      num-workers: 2
    # for testing
    disable-bean:
      event-expiry-service: false
      event-queue-snapshot-service: false
      only-once-event-service: false
      event-publisher: false
  strictly-once-event:
    event-duration-millis: 10000
    max-events: 10000
    key-prefix: "strictly-once"
    web-socket:
      element: "strictly-once"
    event-queue:
      num-workers: 2
  time-sync:
    num-frames: 20
  redis:
    functions-resource: redis/redis_functions.lua
    # for testing
    disable-bean:
      redis-connection-factory: false
      string-redis-template: false
      event-time-redis-template: false
      string-long-redis-template: false


logging:
  level:
    org:
      springframework: info
    com:
      ericgha: debug