
spring:
  data:
    redis:
      client-type: jedis
      host: "localhost"
      port: 6379
app:
  event-duration-millis: 10000
  redis:
    retry:
      # configured to do 4 retries (in addition to initial call) (0.5, 1.25, 2.375, 4.063 sec)
      initial-interval: 500
      multiplier: 1.5
      max-interval: 4500

logging:
  level:
    org:
      springframework: debug