version: "3.9"

# For dev, loads redis_functions.lua from scripts dir as a bind mount

services:

    redis-container:
        image: redis:7
        command: /opt/sh/start-redis.sh
        ports:
            - "6379:6379"
        environment:
            - REDIS_REPLICATION_MODE=master
        volumes:
            - redis-data:/var/lib/redis
            - ./scripts/:/opt/

volumes:

    redis-data:
        name: redis-data
        external: false


